In [1]:
import numpy as np

In [13]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [16]:
list_np=np.array(list)

In [17]:
list_np

array([1, 2, 3, 4, 5])

In [20]:
matrix=([1,2,3],[4,5,6],[7,8,9])
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
matrix1=np.arange(1,18,2)
matrix1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [30]:
matrix2=matrix1.reshape(3,3)
matrix2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [34]:
a=np.random.randint(0,20,10)
a

array([14, 19,  1,  9,  7, 12,  3,  0, 14,  9])

In [41]:
a=np.arange(1,6).reshape(5,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [42]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[3]


3

In [48]:
arr[4]

4

In [49]:
arr[9]

9

In [56]:
arr[0:11:2]

array([0, 2, 4, 6, 8])

In [57]:
arr[7:10]=100
arr

array([  0,   1,   2,   3,   4,   5,   6, 100, 100, 100])

In [73]:
arr2=np.arange(0,25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr2[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])